### ISSUE TITLE
File system freezes in the rename method

### ISSUE THREAD

**Issue by arvgord** [SerCeMan/jnr-fuse#85]
Hi, @SerCeMan.

I found that a file system freezes in the rename method when I try to get all files in the selected folder(I need to check that a folder is empty before renaming) using  `Files.newDirectoryStream(some_folder)`(or another method).
I reproduced this in the jnr-fuse MemoryFs example.  
![test-rename](https://user-images.githubusercontent.com/39695947/68764638-a8a73400-064d-11ea-9ac7-7129479da3ba.png)

**Comment by SerCeMan** [comment]
Hey, @arvgord! Can it be that you're trying to invoke fuse from fues?

**Comment by arvgord** [comment]
Yes, that's right.

**Comment by SerCeMan** [comment]
Hey, @arvgord! Sorry for the delay, I believe that's expected behaviour. As far as I can see from the code sample, the `rename` method tries to operate on a higher level than it should by performing a syscall rather than manipulating the structure directly. For instance, in this case what rename is expected to do in the `MemoryFs` example is to manipulate the in-memory structure so that the next read can see observe the file at the new location.

**Comment by SerCeMan** [comment]
I'm going ahead and closing this issue now, but feel free to reopen if you see any issues with jnr-fuse :)
